# Generated by Django 5.0 on 2023-12-05 15:57

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='title', max_length=55, null=True, unique=True)),
                ('content', models.TextField(blank=True, help_text='content', max_length=2048, null=True)),
                ('slug', models.SlugField(default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='updated at')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
